### ISSUE TITLE
Not running with defaults 

### ISSUE THREAD

**Issue by msh855** [european-central-bank/BEAR-toolbox#4]
Thanks for the good tool. But so far I fail to run it based on your excel file. 

I use the tool on Mac using a Matlab 2021  getting this error:
```

Unrecognized function or variable 'xlwrite'.

Error in xlswritegeneral (line 34)
    status=xlwrite(replace(file,'\',filesep),data,sheet,range);

Error in loadsignres (line 626)
    xlswritegeneral([pref.datapath filesep 'results' filesep pref.results_sub '.xlsx'],strngs1,'sign res values','B2');

Error in bear_toolbox_main_code (line 124)
    [signrestable,signresperiods,signreslabels,strctident,favar]=loadsignres(n,endo,pref,favar,IRFt,strctident);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in bear5 (line 53)
    run(fullfile('files','bear_toolbox_main_code.m'));
```

is it because of Mac and Matlab 2021 ?

**Comment by Thidmg** [comment]
hi, i'm having problem  to run favar with default sentings and data, i only changed the period time
so i don't think is because of mac, but my error is different than yours


![favarbear](https://user-images.githubusercontent.com/74992941/122679490-78c4f880-d1c1-11eb-82bd-082523c1f72a.png)



my error is:


Index in position 1 exceeds array bounds.

Error in favar_gensample2 (line 89)
    data_exfactors_stddev_temp=std(favar.data_exfactors(1:favar.informationendlocation_sub,:));

Error in gensample (line 51)
    [data,variablestrings,favar]=favar_gensample2(data1,endo,variablestrings,startlocation,lags,favar);

Error in bear_toolbox_main_code (line 93)
        =gensample(startdate,enddate,VARtype,Fstartdate,Fenddate,Fendsmpl,endo,exo,frequency,lags,F,CF,ar,lambda4,PriorExcel,priorsexogenous,pref,favar,IRFt);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in bear5 (line 53)
    run(fullfile('files','bear_toolbox_main_code.m'));

**Comment by ebenetce** [comment]
Hello @msh855, could you try it with the new release that was just posted? This should work in MAC and 2021a
